# Generated by Django 3.1.4 on 2020-12-24 19:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='user',
            name='description',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_creator',
        ),
        migrations.RemoveField(
            model_name='user',
            name='location',
        ),
        migrations.RemoveField(
            model_name='user',
            name='updated_on',
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='test@example.ru', max_length=254, unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
